title: Lee and Seong (2024)
page-top-title: Lee and Seong (2024)
top-section-bg-text: Are the Bank of Korea's Inflation Forecasts Biased Toward the Target?
home-subtitle: Forecast Plots
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
